init_db.py
=> update drop down menus

init_db.py
added options for noshow_reason
added/revised options for noapt_reason
=> more updating of options from Radhika

init_db.py
changed ethnicities
adjusted diagnosis categories
=> adjustments to drop down menu options

pttrack/followup_models.py, pttrack/forms.py, pttrack/models.py, pttrack/tests.py
=> Addition of alternate phone number owner

clintools/base_settings.py, pttrack/admin.py, pttrack/followup_models.py, pttrack/models.py, requirements.txt
Addresses Issue #10. This will require a migration of the serverside database, as well as an update the the installed libraries. The whole nine yards.
@nakul2234  I want to merge this so it's live ASAP (*i.e.* before clinic tomorrow) but I want to make I don't disrupt your dev environment so give me a call if you have problems?
=> Add revision history to Notes, People

pttrack/followup_models.py, pttrack/tests.py, pttrack/views.py
Addressing #17 . This should help with the AI-clear->followup-creation->AI-create workflow.
=> Failed Contact redirects to AI Creation

pttrack/models.py, pttrack/tests.py
=> Add Country field

pttrack/forms.py, pttrack/models.py, pttrack/templates/pttrack/patient_detail.html, pttrack/templates/pttrack/patient_list.html, pttrack/templates/pttrack/patient_list_expanded.html, pttrack/tests.py, pttrack/urls.py, pttrack/views.py
Now there will be an activating patient feature in the Patient Detail Page that will allow coordinators to manage patients that are in the digest views and being checked. Also, I made the digest views for attendings and for coordinators to have a bit more information splitting up patients.
=> Added feature of activating patients to make digest views more useful

.travis.yml, README.md, pttrack/forms.py, pttrack/test_forms.py, pttrack/test_validators.py, pttrack/test_views.py
Substantial rewrites of some tests to improve coverage and use of the unit test framework. Also begin to split test_views.py out into more files, because it's a beast right now.
Additionally, add [codecov](https://codecov.io) coverage analysis.
Obviously, more work needs to be done, but we're getting there.
=> Unit Test Refactoring

api/serializers.py, osler.sublime-project, pttrack/forms.py, pttrack/templates/pttrack/patient_list.html, pttrack/test_views.py
Addressing #116, put a column for the most recent attesting physician on the all patients view.
=> Attestation Column on All Patients

api/serializers.py, api/test.py, api/views.py, demographics/forms.py, osler.sublime-project, pttrack/forms.py, pttrack/migrations/0008_add_case_manager.py, pttrack/models.py, pttrack/templates/pttrack/patient_list.html, pttrack/test_forms.py, pttrack/test_views.py, pttrack/views.py
1) It should be possible to attach a case manager to patients
2) Case Manager should be allowed to filter (?) for their patients?
=> Add Case Manager to Patients

osler/deploy_settings.py, workup/views.py
1. Add Minerva to recipients of 5xx error emails
1. Update error message for >1 clinic day to be more clear
=> Update Error Handling

pttrack/test_views.py, workup/forms.py, workup/test_forms.py
Fix an error where failure to specify units would not be nicely validated.
=> Fix WU Form Errors

api/test.py, api/views.py, pttrack/migrations/0002_auto_20171007_1533.py, pttrack/models.py, pttrack/templates/pttrack/patient_detail.html, pttrack/test_views.py, pttrack/views.py
didn't really try that hard to make new tests but hopefully its ok
=> priority action item feature

pttrack/forms.py, pttrack/management/commands/action_item_spam.py, pttrack/migrations/0003_auto_20171014_1843.py, pttrack/models.py, pttrack/templates/pttrack/patient_detail.html, pttrack/test_views.py, workup/templates/workup/workup_body.html
Maybe don't need to make tests at all??
=> added second case manager field by request

demographics/forms.py, demographics/migrations/0002_historicalrecords_and_nullboolean_20171119_1818.py, demographics/models.py, demographics/templates/demographics/demographics-create.html, demographics/templates/demographics/demographics-resolve.html, demographics/tests.py, demographics/views.py, osler/debug_settings.py
=> Demographics error handling

README.md
Added instructions for reset_db.bat
=> Updated README for Windows users

demographics/forms.py
=> Added datetimepicker for last ER visit

appointment/test_views.py, followup/fixtures/followup.json, pttrack/decorators.py, pttrack/fixtures/pttrack.json, pttrack/test_views.py, pttrack/urls.py, referral/models.py, requirements.txt, scripts/init_db.py, workup/fixtures/workup.json
=> Upgrade to django 1.11

osler/deploy_settings.py, osler/wsgi.py
* add strict integrity checks for MySQL
* fix `wsgi.py` for use with Django 1.11
* remove some admins from admin list
=> Update configurations for django 1.11

osler/base_settings.py, pttrack/models.py, pttrack/templates/pttrack/base.html, pttrack/templates/pttrack/blurbs/action-item-blurb-active.html, pttrack/urls.py, referral/forms.py, referral/models.py, referral/templates/referral/new-patient-contact.html, referral/templates/referral/select-referral.html, referral/tests.py, referral/urls.py, referral/views.py
Fix issue where wrong blurb was used for ReferralFollowup, leading to inability to mark ReferralFollowups done.
=> ReferralFollowup mark as done functionality

pttrack/models.py, pttrack/templates/pttrack/blurbs/action-item-blurb-active.html, referral/models.py
Fix an issue where the blurb would fail to link the admin panel correctly for referrals.
=> Fix admin link on action item blurb for referral
